name: tarkin

library:
  source-dirs: src
  dependencies:
    - base
    - bytestring
    - http-conduit
    - lens
    - proto-lens
    - proto-lens-runtime
    - random-shuffle
    - random
    - scotty
    - split
    - text
  ghc-options:
    # https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wpartial-fields
    - -Wmissing-home-modules
    - -Widentities
    - -Wredundant-constraints
    - -Wmonomorphism-restriction
    - -Wno-unused-top-binds

  exposed-modules:
    - Core.Main

executables:
  tarkin-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - tarkin

tests:
  tarkin-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - tarkin
